/**
 * epub-rs C API
 *
 * Opaque-handle, JSON-centric C interface for the epub-rs EPUB processing library.
 *
 * Memory ownership rules:
 *  - All functions returning `char *` must be freed with `epub_free_string()`.
 *  - All functions returning `uint8_t *` must be freed with `epub_free_bytes(ptr, len)`.
 *  - Handles from `epub_open*` must be freed with `epub_free()`.
 *  - Passing NULL for any pointer parameter is always safe (returns NULL, sets error).
 *
 * Error handling:
 *  - On failure every function returns NULL.
 *  - Call `epub_last_error()` immediately after for a human-readable description.
 *  - The error string is valid until the next FFI call on the same thread.
 */


#ifndef EPUB_RS_H
#define EPUB_RS_H

#pragma once

/* Auto-generated by cbindgen — DO NOT EDIT. Run `cargo build --features ffi` to regenerate. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Default bytes per reading position, matching the Adobe RMSDK and Readium standard.
 *
 * See: <https://github.com/readium/architecture/issues/123>
 */
#define BYTES_PER_POSITION 1024

/**
 * Opaque EPUB archive handle.
 *
 * Allocated by `epub_open` / `epub_open_file`, freed by `epub_free`.
 * C code must never attempt to inspect or copy the pointed-to memory.
 */
typedef struct epub_t epub_t;

/**
 * Open an EPUB from a byte buffer.
 *
 * `data` must point to at least `len` bytes of a valid ZIP/EPUB file.
 * Returns an opaque handle on success, `NULL` on failure.
 * The caller is responsible for freeing the handle with `epub_free()`.
 *
 * # Safety
 * `data` must be a valid pointer to `len` contiguous, readable bytes.
 * The pointer does not need to remain valid after this function returns.
 */
struct epub_t *epub_open(const unsigned char *data, size_t len);

/**
 * Open an EPUB from a file-system path (UTF-8 encoded, null-terminated).
 *
 * Returns an opaque handle on success, `NULL` on failure.
 * The caller is responsible for freeing the handle with `epub_free()`.
 *
 * # Safety
 * `path` must be a valid null-terminated C string.
 */
struct epub_t *epub_open_file(const char *path);

/**
 * Free an EPUB handle.
 *
 * Safe to call with `NULL` (no-op). After this call the pointer is invalid.
 *
 * # Safety
 * `handle` must either be `NULL` or a pointer previously returned by an
 * `epub_open*` function that has not yet been freed.
 */
void epub_free(struct epub_t *handle);

/**
 * Parse the EPUB and return book metadata as a JSON string.
 *
 * After the first call the result is cached; subsequent calls are cheap.
 * The caller must free the returned string with `epub_free_string()`.
 * Returns `NULL` on failure — call `epub_last_error()` for details.
 *
 * JSON shape: `EpubBook` — see `src/model.rs` for field documentation.
 *
 * # Safety
 * `handle` must be a valid non-null pointer obtained from `epub_open*`.
 */
char *epub_parse(struct epub_t *handle);

/**
 * Return all navigation data (TOC + page-list + landmarks) as a JSON string.
 *
 * The EPUB navigation file is read and parsed only once; results are returned
 * directly without an internal cache (navigation is rarely called multiple times).
 *
 * JSON shape:
 * ```json
 * {
 *   "toc":       [{"title":"Ch1","href":"ch1.xhtml","children":[...]}, ...],
 *   "page_list": [{"title":"1","href":"ch1.xhtml#p1","children":[]}, ...],
 *   "landmarks": [{"title":"Begin Reading","href":"ch1.xhtml","children":[]}, ...]
 * }
 * ```
 *
 * The caller must free the returned string with `epub_free_string()`.
 * Returns `NULL` on failure.
 *
 * # Safety
 * `handle` must be a valid non-null pointer obtained from `epub_open*`.
 */
char *epub_get_navigation(struct epub_t *handle);

/**
 * Return the Table of Contents as a JSON array of `TocEntry` objects.
 *
 * Convenience wrapper around `epub_get_navigation`. Prefer
 * `epub_get_navigation` when you also need page-list or landmarks,
 * to avoid re-reading the navigation file.
 *
 * The caller must free the returned string with `epub_free_string()`.
 *
 * # Safety
 * `handle` must be a valid non-null pointer obtained from `epub_open*`.
 */
char *epub_get_toc(struct epub_t *handle);

/**
 * Return the page list as a JSON array of `TocEntry` objects.
 *
 * Each entry has `title` = print page label (`"1"`, `"42"`, `"xii"`) and
 * `href` = document position (typically with a fragment: `"ch3.xhtml#p42"`).
 *
 * Returns a JSON empty array `[]` if no page list is present.
 * The caller must free the returned string with `epub_free_string()`.
 *
 * # Safety
 * `handle` must be a valid non-null pointer obtained from `epub_open*`.
 */
char *epub_get_page_list(struct epub_t *handle);

/**
 * Return reading positions grouped by spine item as a JSON 2-D array.
 *
 * `bytes_per_position`: granularity of reflowable positions in bytes.
 * Pass `0` to use the Readium/Adobe default of 1024 bytes.
 *
 * JSON shape: `[[{Position}, ...], ...]`  — outer index = spine item index.
 * The caller must free the returned string with `epub_free_string()`.
 *
 * # Safety
 * `handle` must be a valid non-null pointer obtained from `epub_open*`.
 */
char *epub_positions_by_reading_order(struct epub_t *handle, size_t bytes_per_position);

/**
 * Return the cover image bytes.
 *
 * On success:
 * - The return value is a pointer to `*out_len` bytes of image data.
 *   Free with `epub_free_bytes(ptr, *out_len)`.
 * - `*out_media_type` is a null-terminated media-type string (e.g. `"image/jpeg"`).
 *   Free with `epub_free_string(*out_media_type)`.
 *
 * Returns `NULL` on failure; `out_len` and `out_media_type` are left unchanged.
 *
 * # Safety
 * - `handle` must be a valid non-null pointer obtained from `epub_open*`.
 * - `out_len` and `out_media_type` must be valid non-null writable pointers.
 */
unsigned char *epub_get_cover_image(struct epub_t *handle, size_t *out_len, char **out_media_type);

/**
 * Return the raw bytes of a manifest resource identified by its `href`.
 *
 * `href` is the relative href as it appears in the EPUB manifest
 * (e.g. `"OEBPS/chapter1.xhtml"` or just `"chapter1.xhtml"`).
 *
 * On success the return value points to `*out_len` bytes. Free with
 * `epub_free_bytes(ptr, *out_len)`. Returns `NULL` on failure.
 *
 * # Safety
 * - `handle` must be a valid non-null pointer obtained from `epub_open*`.
 * - `href` must be a valid null-terminated C string.
 * - `out_len` must be a valid non-null writable pointer.
 */
unsigned char *epub_get_resource(struct epub_t *handle, const char *href, size_t *out_len);

/**
 * Resolve a CFI string to a structured DOM location descriptor.
 *
 * This is a **stateless** function — it does not require a loaded EPUB handle.
 *
 * JSON shape:
 * ```json
 * {
 *   "start": {
 *     "spine_index": 1,
 *     "steps": [{"node_type": "element", "index": 2, "id": "section1"}, ...],
 *     "xpath": "//*[@id='section1']/...",
 *     "id_shortcut": "para5",
 *     "character_offset": 3,
 *     "is_text_node": true
 *   },
 *   "end": null
 * }
 * ```
 *
 * The caller must free the returned string with `epub_free_string()`.
 * Returns `NULL` on failure — call `epub_last_error()` for details.
 *
 * # Safety
 * `cfi_str` must be a valid null-terminated C string.
 */
char *epub_resolve_cfi(const char *cfi_str);

/**
 * Return the error message from the most recent failed call on this thread.
 *
 * Returns `NULL` if the last call succeeded.
 * The returned pointer is valid until the next FFI call on the same thread.
 * Do **not** free this pointer — it is thread-local storage.
 */
const char *epub_last_error(void);

/**
 * Free a `char *` returned by any epub-rs function.
 *
 * Safe to call with `NULL` (no-op).
 *
 * # Safety
 * `s` must either be `NULL` or a pointer previously returned by an epub-rs
 * function that returns `char *`, and must not have been freed already.
 */
void epub_free_string(char *s);

/**
 * Free a byte buffer returned by any epub-rs function.
 *
 * `buf` must be the pointer and `len` must be the exact length originally
 * written to the `out_len` parameter. Safe to call with a `NULL` `buf` (no-op).
 *
 * # Safety
 * `buf` must either be `NULL` or a pointer previously returned by an epub-rs
 * function that returns `uint8_t *`, paired with the matching `len`.
 * Must not have been freed already.
 */
void epub_free_bytes(unsigned char *buf, size_t len);

#endif  /* EPUB_RS_H */
