/**
 * epub-rs C API
 *
 * Opaque-handle, JSON-centric C interface for the epub-rs EPUB processing library.
 *
 * Memory ownership rules:
 *  - All functions returning `char *` must be freed with `epub_free_string()`.
 *  - All functions returning `uint8_t *` must be freed with `epub_free_bytes(ptr, len)`.
 *  - Handles from `epub_open*` must be freed with `epub_free()`.
 *  - Passing NULL for any pointer parameter is always safe (returns NULL, sets error).
 *
 * Error handling:
 *  - On failure every function returns NULL.
 *  - Call `epub_last_error()` immediately after for a human-readable description.
 *  - The error string is valid until the next FFI call on the same thread.
 */


#ifndef EPUB_RS_H
#define EPUB_RS_H

#pragma once

/* Auto-generated by cbindgen — DO NOT EDIT. Run `cargo build --features ffi` to regenerate. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Default bytes per reading position, matching the Adobe RMSDK and Readium standard.
 *
 * See: <https://github.com/readium/architecture/issues/123>
 */
#define BYTES_PER_POSITION 1024

/**
 * Opaque EPUB generator handle.
 *
 * Allocated by `epub_generator_new()`, freed by `epub_generator_free()`.
 */
typedef struct EpubGeneratorHandle EpubGeneratorHandle;

/**
 * Opaque EPUB archive handle.
 *
 * Allocated by `epub_open` / `epub_open_file`, freed by `epub_free`.
 * C code must never attempt to inspect or copy the pointed-to memory.
 */
typedef struct epub_t epub_t;

/**
 * Open an EPUB from a byte buffer.
 *
 * `data` must point to at least `len` bytes of a valid ZIP/EPUB file.
 * Returns an opaque handle on success, `NULL` on failure.
 * The caller is responsible for freeing the handle with `epub_free()`.
 *
 * # Safety
 * `data` must be a valid pointer to `len` contiguous, readable bytes.
 * The pointer does not need to remain valid after this function returns.
 */
struct epub_t *epub_open(const unsigned char *data, size_t len);

/**
 * Open an EPUB from a file-system path (UTF-8 encoded, null-terminated).
 *
 * Returns an opaque handle on success, `NULL` on failure.
 * The caller is responsible for freeing the handle with `epub_free()`.
 *
 * # Safety
 * `path` must be a valid null-terminated C string.
 */
struct epub_t *epub_open_file(const char *path);

/**
 * Free an EPUB handle.
 *
 * Safe to call with `NULL` (no-op). After this call the pointer is invalid.
 *
 * # Safety
 * `handle` must either be `NULL` or a pointer previously returned by an
 * `epub_open*` function that has not yet been freed.
 */
void epub_free(struct epub_t *handle);

/**
 * Parse the EPUB and return book metadata as a JSON string.
 *
 * After the first call the result is cached; subsequent calls are cheap.
 * The caller must free the returned string with `epub_free_string()`.
 * Returns `NULL` on failure — call `epub_last_error()` for details.
 *
 * JSON shape: `EpubBook` — see `src/model.rs` for field documentation.
 *
 * # Safety
 * `handle` must be a valid non-null pointer obtained from `epub_open*`.
 */
char *epub_parse(struct epub_t *handle);

/**
 * Return all navigation data (TOC + page-list + landmarks) as a JSON string.
 *
 * The EPUB navigation file is read and parsed only once; results are returned
 * directly without an internal cache (navigation is rarely called multiple times).
 *
 * JSON shape:
 * ```json
 * {
 *   "toc":       [{"title":"Ch1","href":"ch1.xhtml","children":[...]}, ...],
 *   "page_list": [{"title":"1","href":"ch1.xhtml#p1","children":[]}, ...],
 *   "landmarks": [{"title":"Begin Reading","href":"ch1.xhtml","children":[]}, ...]
 * }
 * ```
 *
 * The caller must free the returned string with `epub_free_string()`.
 * Returns `NULL` on failure.
 *
 * # Safety
 * `handle` must be a valid non-null pointer obtained from `epub_open*`.
 */
char *epub_get_navigation(struct epub_t *handle);

/**
 * Return the Table of Contents as a JSON array of `TocEntry` objects.
 *
 * Convenience wrapper around `epub_get_navigation`. Prefer
 * `epub_get_navigation` when you also need page-list or landmarks,
 * to avoid re-reading the navigation file.
 *
 * The caller must free the returned string with `epub_free_string()`.
 *
 * # Safety
 * `handle` must be a valid non-null pointer obtained from `epub_open*`.
 */
char *epub_get_toc(struct epub_t *handle);

/**
 * Return the page list as a JSON array of `TocEntry` objects.
 *
 * Each entry has `title` = print page label (`"1"`, `"42"`, `"xii"`) and
 * `href` = document position (typically with a fragment: `"ch3.xhtml#p42"`).
 *
 * Returns a JSON empty array `[]` if no page list is present.
 * The caller must free the returned string with `epub_free_string()`.
 *
 * # Safety
 * `handle` must be a valid non-null pointer obtained from `epub_open*`.
 */
char *epub_get_page_list(struct epub_t *handle);

/**
 * Return reading positions grouped by spine item as a JSON 2-D array.
 *
 * `bytes_per_position`: granularity of reflowable positions in bytes.
 * Pass `0` to use the Readium/Adobe default of 1024 bytes.
 *
 * JSON shape: `[[{Position}, ...], ...]`  — outer index = spine item index.
 * The caller must free the returned string with `epub_free_string()`.
 *
 * # Safety
 * `handle` must be a valid non-null pointer obtained from `epub_open*`.
 */
char *epub_positions_by_reading_order(struct epub_t *handle, size_t bytes_per_position);

/**
 * Return the cover image bytes.
 *
 * On success:
 * - The return value is a pointer to `*out_len` bytes of image data.
 *   Free with `epub_free_bytes(ptr, *out_len)`.
 * - `*out_media_type` is a null-terminated media-type string (e.g. `"image/jpeg"`).
 *   Free with `epub_free_string(*out_media_type)`.
 *
 * Returns `NULL` on failure; `out_len` and `out_media_type` are left unchanged.
 *
 * # Safety
 * - `handle` must be a valid non-null pointer obtained from `epub_open*`.
 * - `out_len` and `out_media_type` must be valid non-null writable pointers.
 */
unsigned char *epub_get_cover_image(struct epub_t *handle, size_t *out_len, char **out_media_type);

/**
 * Return the raw bytes of a manifest resource identified by its `href`.
 *
 * `href` is the relative href as it appears in the EPUB manifest
 * (e.g. `"OEBPS/chapter1.xhtml"` or just `"chapter1.xhtml"`).
 *
 * On success the return value points to `*out_len` bytes. Free with
 * `epub_free_bytes(ptr, *out_len)`. Returns `NULL` on failure.
 *
 * # Safety
 * - `handle` must be a valid non-null pointer obtained from `epub_open*`.
 * - `href` must be a valid null-terminated C string.
 * - `out_len` must be a valid non-null writable pointer.
 */
unsigned char *epub_get_resource(struct epub_t *handle, const char *href, size_t *out_len);

/**
 * Resolve a CFI string to a structured DOM location descriptor.
 *
 * This is a **stateless** function — it does not require a loaded EPUB handle.
 *
 * JSON shape:
 * ```json
 * {
 *   "start": {
 *     "spine_index": 1,
 *     "steps": [{"node_type": "element", "index": 2, "id": "section1"}, ...],
 *     "xpath": "//*[@id='section1']/...",
 *     "id_shortcut": "para5",
 *     "character_offset": 3,
 *     "is_text_node": true
 *   },
 *   "end": null
 * }
 * ```
 *
 * The caller must free the returned string with `epub_free_string()`.
 * Returns `NULL` on failure — call `epub_last_error()` for details.
 *
 * # Safety
 * `cfi_str` must be a valid null-terminated C string.
 */
char *epub_resolve_cfi(const char *cfi_str);

/**
 * Return the error message from the most recent failed call on this thread.
 *
 * Returns `NULL` if the last call succeeded.
 * The returned pointer is valid until the next FFI call on the same thread.
 * Do **not** free this pointer — it is thread-local storage.
 */
const char *epub_last_error(void);

/**
 * Free a `char *` returned by any epub-rs function.
 *
 * Safe to call with `NULL` (no-op).
 *
 * # Safety
 * `s` must either be `NULL` or a pointer previously returned by an epub-rs
 * function that returns `char *`, and must not have been freed already.
 */
void epub_free_string(char *s);

/**
 * Free a byte buffer returned by any epub-rs function.
 *
 * `buf` must be the pointer and `len` must be the exact length originally
 * written to the `out_len` parameter. Safe to call with a `NULL` `buf` (no-op).
 *
 * # Safety
 * `buf` must either be `NULL` or a pointer previously returned by an epub-rs
 * function that returns `uint8_t *`, paired with the matching `len`.
 * Must not have been freed already.
 */
void epub_free_bytes(unsigned char *buf, size_t len);

/**
 * Return the raw bytes of a manifest resource identified by its manifest **ID**.
 *
 * On success returns a pointer to `*out_len` bytes. Free with `epub_free_bytes(ptr, *out_len)`.
 *
 * # Safety
 * - `handle` must be a valid non-null pointer obtained from `epub_open*`.
 * - `id` must be a valid null-terminated C string.
 * - `out_len` must be a valid non-null writable pointer.
 */
unsigned char *epub_get_resource_by_id(struct epub_t *handle, const char *id, size_t *out_len);

/**
 * Return a chapter's HTML with `data-cfi` attributes injected into every DOM node.
 *
 * `id` is the manifest ID of the spine item (e.g. `"chapter1"`).
 * The caller must free the returned string with `epub_free_string()`.
 *
 * # Safety
 * - `handle` must be a valid non-null pointer obtained from `epub_open*`.
 * - `id` must be a valid null-terminated C string.
 */
char *epub_get_chapter_with_cfi(struct epub_t *handle, const char *id);

/**
 * Search for a literal text query in a chapter. Returns JSON `SearchResult[]`.
 *
 * `id` is the manifest ID; `query` is the literal search string.
 * The caller must free the returned string with `epub_free_string()`.
 *
 * # Safety
 * All pointer parameters must be valid null-terminated C strings.
 * `handle` must be a valid non-null pointer obtained from `epub_open*`.
 */
char *epub_search_chapter(struct epub_t *handle, const char *id, const char *query);

/**
 * Return semantic content blocks (paragraphs, headings) for a chapter as JSON `ContentElement[]`.
 *
 * `id` is the manifest ID of the chapter. The caller must free the returned string with `epub_free_string()`.
 *
 * # Safety
 * - `handle` must be a valid non-null pointer obtained from `epub_open*`.
 * - `id` must be a valid null-terminated C string.
 */
char *epub_get_semantic_content(struct epub_t *handle,
                                const char *id);

/**
 * Return a flat JSON array of all reading `Position` objects across the entire EPUB.
 *
 * `bytes_per_position`: pass `0` to use the Readium default of 1024 bytes.
 * The caller must free the returned string with `epub_free_string()`.
 *
 * # Safety
 * `handle` must be a valid non-null pointer obtained from `epub_open*`.
 */
char *epub_generate_locations(struct epub_t *handle, size_t bytes_per_position);

/**
 * Generate positions and build a bidirectional lookup index in one call.
 *
 * Returns a flat JSON array of `Position` objects identical to
 * `epub_generate_locations`. The returned array can be passed as `positions_json`
 * to `epub_location_from_cfi` and `epub_cfi_from_location`.
 *
 * The difference from `epub_generate_locations` is semantic: this function
 * is designed to be paired with the lookup functions below.
 *
 * `bytes_per_position`: pass `0` to use the Readium default of 1024 bytes.
 * The caller must free the returned string with `epub_free_string()`.
 *
 * # Safety
 * `handle` must be a valid non-null pointer obtained from `epub_open*`.
 */
char *epub_generate_location_index(struct epub_t *handle, size_t bytes_per_position);

/**
 * Find the 0-based position index that contains a given CFI.
 *
 * `positions_json`: the JSON array returned by `epub_generate_location_index`
 * or `epub_generate_locations`.
 * `cfi_str`: any valid EPUB CFI string (bookmark, annotation, or position CFI).
 *
 * Returns the 0-based index as a JSON number (e.g. `"42"`), or `"-1"` if the
 * CFI could not be resolved (wrong spine item, parse error, or empty list).
 *
 * The caller must free the returned string with `epub_free_string()`.
 *
 * **Algorithm**: O(|cfi_str|) — parses the CFI once, then uses integer arithmetic
 * on pre-computed chapter offsets. No binary search.
 *
 * # Safety
 * - `handle` must be a valid non-null pointer obtained from `epub_open*`.
 * - `positions_json` and `cfi_str` must be valid null-terminated C strings.
 */
char *epub_location_from_cfi(struct epub_t *handle,
                             const char *positions_json,
                             const char *cfi_str);

/**
 * Return the CFI string for a given 0-based position index.
 *
 * `positions_json`: the JSON array returned by `epub_generate_location_index`.
 * `idx`: 0-based position index (as returned by `epub_location_from_cfi`).
 *
 * Returns the CFI string (e.g. `"epubcfi(/6/4!/4/2)"`), or `NULL` if `idx`
 * is out of range. The caller must free with `epub_free_string()`.
 *
 * O(1) — direct array access.
 *
 * # Safety
 * - `handle` must be a valid non-null pointer obtained from `epub_open*`.
 * - `positions_json` must be a valid null-terminated C string.
 */
char *epub_cfi_from_location(struct epub_t *handle, const char *positions_json, size_t idx);

/**
 * Compare two CFI strings numerically per the EPUB CFI spec.
 *
 * Returns: `-1` if `cfi_a < cfi_b`, `0` if equal, `1` if `cfi_a > cfi_b`.
 * On parse error returns `INT32_MIN` and sets `epub_last_error()`.
 *
 * # Safety
 * Both `cfi_a` and `cfi_b` must be valid null-terminated C strings.
 */
int32_t epub_compare_cfi(const char *cfi_a, const char *cfi_b);

/**
 * Combine two Point CFIs into a spec-compliant range CFI string.
 *
 * Output format: `epubcfi(shared,start_local,end_local)`.
 * The caller must free the returned string with `epub_free_string()`.
 * Returns `NULL` on failure.
 *
 * # Safety
 * Both `start_cfi` and `end_cfi` must be valid null-terminated C strings.
 */
char *epub_generate_cfi_range(const char *start_cfi, const char *end_cfi);

/**
 * Decrypt an obfuscated font file (IDPF or Adobe algorithm).
 *
 * - `data` / `len`: encrypted font bytes.
 * - `epub_identifier`: the EPUB's unique identifier string (null-terminated).
 * - `is_idpf`: `1` for IDPF algorithm, `0` for Adobe.
 * - `out_len`: receives the number of decrypted bytes.
 *
 * Returns a pointer to decrypted bytes. Free with `epub_free_bytes(ptr, *out_len)`.
 * Returns `NULL` on failure.
 *
 * # Safety
 * - `data` must point to at least `len` readable bytes.
 * - `epub_identifier` and must be valid null-terminated C strings.
 * - `out_len` must be a valid non-null writable pointer.
 */
unsigned char *epub_decrypt_font(const unsigned char *data,
                                 size_t len,
                                 const char *epub_identifier,
                                 int32_t is_idpf,
                                 size_t *out_len);

/**
 * Create a new EPUB generator.
 *
 * Returns an opaque handle on success. Free with `epub_generator_free()`.
 */
struct EpubGeneratorHandle *epub_generator_new(void);

/**
 * Free an EPUB generator handle. Safe to call with `NULL`.
 *
 * # Safety
 * `handle` must be `NULL` or a pointer from `epub_generator_new()` not yet freed.
 */
void epub_generator_free(struct EpubGeneratorHandle *handle);

/**
 * Set the EPUB title.
 *
 * # Safety
 * `handle` and `title` must be valid non-null pointers.
 */
void epub_generator_set_title(struct EpubGeneratorHandle *handle, const char *title);

/**
 * Set the EPUB language (e.g. `"en"`, `"zh-CN"`).
 *
 * # Safety
 * `handle` and `lang` must be valid non-null pointers.
 */
void epub_generator_set_language(struct EpubGeneratorHandle *handle, const char *lang);

/**
 * Set the EPUB unique identifier (e.g. UUID or ISBN).
 *
 * # Safety
 * `handle` and `identifier` must be valid non-null pointers.
 */
void epub_generator_set_identifier(struct EpubGeneratorHandle *handle, const char *identifier);

/**
 * Add a creator/author to the EPUB metadata.
 *
 * `role` may be `NULL` (defaults to no role). Use standard MARC relator codes, e.g. `"aut"`.
 *
 * # Safety
 * `handle` and `name` must be valid non-null pointers; `role` may be `NULL`.
 */
void epub_generator_add_author(struct EpubGeneratorHandle *handle,
                               const char *name,
                               const char *role);

/**
 * Add an HTML chapter to the EPUB manifest and spine.
 *
 * - `id`: unique manifest ID.
 * - `href`: relative path within the EPUB (e.g. `"text/ch1.xhtml"`).
 * - `html`: null-terminated UTF-8 HTML content.
 *
 * # Safety
 * All pointers must be valid non-null null-terminated C strings.
 */
void epub_generator_add_chapter(struct EpubGeneratorHandle *handle,
                                const char *id,
                                const char *href,
                                const char *html);

/**
 * Add an HTML chapter and simultaneously add it to the Table of Contents.
 *
 * # Safety
 * All pointers must be valid non-null null-terminated C strings.
 */
void epub_generator_add_chapter_with_nav(struct EpubGeneratorHandle *handle,
                                         const char *id,
                                         const char *href,
                                         const char *title,
                                         const char *html);

/**
 * Add a binary resource (image, font, CSS, etc.) to the EPUB.
 *
 * - `id`: unique manifest ID.
 * - `href`: relative path (e.g. `"images/cover.jpg"`).
 * - `media_type`: MIME type (e.g. `"image/jpeg"`).
 * - `data` / `len`: raw bytes.
 *
 * # Safety
 * String pointers must be valid null-terminated C strings.
 * `data` must point to at least `len` readable bytes.
 */
void epub_generator_add_resource(struct EpubGeneratorHandle *handle,
                                 const char *id,
                                 const char *href,
                                 const char *media_type,
                                 const unsigned char *data,
                                 size_t len);

/**
 * Set the EPUB cover image.
 *
 * # Safety
 * String pointers must be valid null-terminated C strings.
 * `data` must point to at least `len` readable bytes.
 */
void epub_generator_set_cover(struct EpubGeneratorHandle *handle,
                              const char *href,
                              const char *media_type,
                              const unsigned char *data,
                              size_t len);

/**
 * Add a landmark (structural reference) to the EPUB navigation.
 *
 * `epub_type`: landmark type, e.g. `"cover"`, `"toc"`, `"bodymatter"`.
 *
 * # Safety
 * All pointers must be valid non-null null-terminated C strings.
 */
void epub_generator_add_landmark(struct EpubGeneratorHandle *handle,
                                 const char *epub_type,
                                 const char *href,
                                 const char *title);

/**
 * Add a page-list entry (print page mapping).
 *
 * # Safety
 * `name` and `href` must be valid non-null null-terminated C strings.
 */
void epub_generator_add_page(struct EpubGeneratorHandle *handle,
                             const char *name,
                             const char *href);

/**
 * Set the complete Table of Contents from a JSON-encoded array of `TocEntry` objects.
 *
 * This replaces any TOC entries added by `epub_generator_add_chapter_with_nav()`.
 * Accepts nested TOC trees (each `TocEntry` may have a `children` array).
 *
 * `toc_json` must be a valid null-terminated UTF-8 JSON string, e.g.:
 * ```json
 * [{"title":"Chapter 1","href":"text/ch1.xhtml","children":[]},
 *  {"title":"Chapter 2","href":"text/ch2.xhtml","children":[
 *    {"title":"Section 2.1","href":"text/ch2.xhtml#s1","children":[]}]}]
 * ```
 * Returns `1` on success, `0` on failure (call `epub_last_error()` for details).
 *
 * # Safety
 * `handle` and `toc_json` must be valid non-null pointers.
 */
int32_t epub_generator_set_toc(struct EpubGeneratorHandle *handle, const char *toc_json);

/**
 * Set all EPUB metadata at once from a JSON-encoded `Metadata` object.
 *
 * Replaces any individual metadata set by `epub_generator_set_title()`, etc.
 * All fields are optional; missing fields in the JSON keep their default values.
 *
 * Example JSON:
 * ```json
 * {"title":"My Book","language":"en","creators":[{"name":"Alice","role":"aut"}]}
 * ```
 * Returns `1` on success, `0` on failure (call `epub_last_error()` for details).
 *
 * # Safety
 * `handle` and `metadata_json` must be valid non-null pointers.
 */
int32_t epub_generator_set_metadata(struct EpubGeneratorHandle *handle, const char *metadata_json);

/**
 * Validate the generator state without producing any output.
 *
 * Runs the same pre-flight checks as `epub_generator_build()` (required
 * fields, non-empty spine, etc.) but does **not** consume the handle.
 * The generator remains usable after this call.
 *
 * Returns `1` if the current state would produce a valid EPUB, `0` otherwise.
 * On failure, `epub_last_error()` returns a human-readable description.
 *
 * # Safety
 * `handle` must be a valid non-null pointer.
 */
int32_t epub_generator_validate(struct EpubGeneratorHandle *handle);

/**
 * Build the EPUB archive and return it as a byte buffer.
 *
 * On success writes the EPUB byte count to `*out_len` and returns a pointer
 * to the bytes. Free with `epub_free_bytes(ptr, *out_len)`.
 * Returns `NULL` on failure. The generator handle is **consumed** by this call
 * and must not be used again (it is freed internally).
 *
 * # Safety
 * `handle` must be a valid non-null pointer; `out_len` must be a valid non-null writable pointer.
 */
unsigned char *epub_generator_build(struct EpubGeneratorHandle *handle, size_t *out_len);

#endif  /* EPUB_RS_H */
